# The name of the workflow
name: Skynet API CI/CD 

# This workflow will run on any push to the repository
on: push

jobs:
    test:
        # We set up a virtual machine to run our tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [18.20.3]
              mongodb-version: [5.0.26]

        steps:
        - name: Cloning repo to Ubuntu VM
          uses: actions/checkout@v4.1.5
        
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4.0.2
          with:
            cache-dependency-path: api/package-lock.json
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        
        - name: Install dependencies
          run: | 
           cd api
           npm ci
        
        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.11.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}
        
        - name: Start Node server
          run: npm run start:test &
          env:
            CI: true
        
        - name: Run all tests
          run: |
           cd api
           npm test
          env:
            CI: true
